### ISSUE TITLE
Dialog pops up when clicking on Compound Details

### ISSUE THREAD

**Issue by epoyraz** [EBI-Metabolights/MetaboLights#1]
Hi there,
When i click, for example 
http://www.ebi.ac.uk/metabolights/MTBLC10136
i get a dialog saying : 
"Cannot fetch Compound details"

This is the output of the console : 
![bildschirmfoto 2016-03-03 um 03 57 54](https://cloud.githubusercontent.com/assets/1207226/13483410/5801846a-e0f4-11e5-8886-b2e8e847a747.png)

Browser : Chrome

**Comment by egonw** [comment]
Yeah, I have that too... this is the end result: a dialog but no properties:

![image](https://cloud.githubusercontent.com/assets/26721/14580922/eb0d3e9a-03de-11e6-9c56-b28945a6048c.png)

**Comment by khaug** [comment]
Thank you for reporting this guys.  This was caused by [CTS] (http://cts.fiehnlab.ucdavis.edu), not allowing remote sites to query the web service (CORS).

**Comment by khaug** [comment]
Hmmm.... Now I got the same issue with http://www.ebi.ac.uk/metabolights/beta/MTBLC17750.  Obviously still ongoing

**Comment by CS76** [comment]
Are you still getting any error on the BETA page? If so pls send me a screen shot. I just looked into the details, so far no issues other than the MS spectra

**Comment by khaug** [comment]
Thanks @CS76
