### ISSUE TITLE
mysubmissions pagination broken

### ISSUE THREAD

**Issue by sneumann** [EBI-Metabolights/MetaboLights#10]
Hi, 
if I am in http://www.ebi.ac.uk/metabolights/mysubmissions
and then click on ">" to get page2, this links to http://www.ebi.ac.uk/metabolights/mysubmissions#
but in fact what's displayed is http://www.ebi.ac.uk/metabolights/search

23536 results, showing 11 to 20 ...

**Comment by khaug** [comment]
We had a larger Lucene index refresh, do you still see this?

**Comment by sneumann** [comment]
I am afraid yes:
`23560 results, showing 11 to 20`

**Comment by CS76** [comment]
Resolved now
