### ISSUE TITLE
Share study link is not present

### ISSUE THREAD

**Issue by RonanDaly** [EBI-Metabolights/MetaboLights#25]
According to the update study page, ```To share a private study with journals and reviewers, please use the information available under the "Share study" link available on your study details page.``` On the study I have just uploaded (MTBLS883), this link appears not to be present on the study details page. If you could advise an alternative way to share the study, that would be great.

**Comment by khaug** [comment]
Dear Ronan

The share study option will become available on the study page when we have completed the curation process and the study is available for review.  

When you have completed your study upload, you must change the study status to "In Curation" (under the Actions menu) to move the study into our curation queue. 

Please email "metabolights-help@ebi.ac.uk" off you require further assistance.

Kind regards,
  Ken

**Comment by RonanDaly** [comment]
Thanks Ken - I would still count this as a bug though, as the website doesn't follow the documentation.

**Comment by khaug** [comment]
I guess we can add more information on the update page, but we have chosen to include this information in the confirmation email when a study is created.

“
….
SUBMISSION CHECKLIST - Your study will not be published and made available to the world, until the following conditions have been satisfied:
A. Stage 1 (ISAcreator) validation has successfully passed.
B. Stage 2 (Online) validation has successfully passed.
C. The submitter (you) promotes the study status from Submitted to In Curation (minimum 28 days is required for our validation and curation).
D. The curation team approves the study and moves the study status from In Curation to In Review.
E. Your public release date is reached.

For private pre-publication access to your study, please see the "Share study" link at the top of the study page.
Please note that the pre-publication link is only accessible when the study is in "In Review" status.
"

Kind Regards,
  Ken Haug

**Comment by RonanDaly** [comment]
I think putting the same information as the email would definitely make it clearer. Thanks for your help.
