### ISSUE TITLE
Enhancement: studies by a particular submitter

### ISSUE THREAD

**Issue by sneumann** [EBI-Metabolights/MetaboLights#4]
Hi,

It would be great to have a summary page/search link for all studies 
by a particular submitter, i.e. the one shown on 
http://www.ebi.ac.uk/metabolights/mysubmissions 
as "Submitted by: Steffen Neumann"

Use Case: I can quickly check my (public) studies
for their validation status without having to log in.

Bonus points if these are linked to from the hall of fame on
http://www.ebi.ac.uk/metabolights/statistics

Yours,
Steffen

**Comment by khaug** [comment]
Forgot to add that this is in the MetaboLights backlog

**Comment by khaug** [comment]
This was transferred to the MetaboLights backlog when the request came in. Sorry I did not communicate this.  

Now there is a clickable link in the statistics page (hall of fame) that returns all studies by a submitter.

**Comment by khaug** [comment]
We are also adding a feature in the search result, clicking on the submitters name will show a search result for this submitter, and next to it will be an envelope to send an email.

**Comment by CS76** [comment]
http://www.ebi.ac.uk/metabolights/search?users.fullName=Steffen%20Neumann

done 👍
