### ISSUE TITLE
Bug: MAF files not visible behind reviewer link

### ISSUE THREAD

**Issue by sneumann** [EBI-Metabolights/MetaboLights#6]
Hi, our study http://www.ebi.ac.uk/metabolights/MTBLS338 contains 5 assays, 
where Assays 2,4,5 contain characterised metabolites. These are visible 
when properly logged in, but they are not shown to reviewers when using 
the http://www.ebi.ac.uk/metabolights/reviewer137e5003-6a2a-41e9-a0a1-63d598a19bf9 link.
Reviewers rightfully complain if no metabolites are visible, and this is bad for a review.
Yours, Steffen

**Comment by khaug** [comment]
We have logged this as a bug now in the ML backlog. sorry

**Comment by khaug** [comment]
Escalated now

**Comment by CS76** [comment]
Resolved
